services:
  frontend:
    build:
      dockerfile: Dockerfile.frontend
    ports:
      - 5173:5173
    
  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    # env_file:
    #   - .env.prisma
    # environment:
    #   - MONGODB_URI=mongodb+srv://mantissa6789:Mantis%402510@cluster0.9ramotn.mongodb.net/dbName=iss